### ISSUE TITLE
data api server in development mode produces no startup output

### ISSUE THREAD

**Issue by danstoner** [iDigBio/idb-backend#123]
When running `idb run-server` in a development environment there is no output to indicate it started or what port it is listening on, etc.

It looks like the code wants to log INFO but that isn't ending up in stdout.

https://github.com/iDigBio/idb-backend/blob/8f612f68be3ea540c7b3616e515e8c2028dc593c/idb/data_api/__init__.py#L94

**Comment by danstoner** [comment]
Possibly just a default logging level issue.

When running with `-v` we do get startup logs...

```
$ idb -v run-server 
2021-01-25 12:04:06.247 INFO  idb.api჻ gevent server @ http://127.0.0.1:19197/ ENV=prod
2021-01-25 12:04:39.804 INFO  idb.api.r჻ 10.228.144.1 - - [25/Jan/2021:12:04:39 -0500] "GET / HTTP/1.1" 200 106 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36" 0/2202
```

**Comment by nrejack** [comment]
Default logging level is WARNING, so that explains this one:
https://github.com/iDigBio/idb-backend/blob/8f612f68be3ea540c7b3616e515e8c2028dc593c/idb/helpers/logging.py#L44-L56

I'll standardize what happens on the idb run-server startup, because we need to get information without having to dig in a log.

**Comment by nrejack** [comment]
Fixed by the above-mentioned commit.
