### ISSUE TITLE
Standardize boto vs boto3 usage

### ISSUE THREAD

**Issue by nrejack** [iDigBio/idb-backend#180]
The ingestion parts of idb-backend use boto < 3.0, which is what gets installed via setup.py. The one-off scripts that live in the scripts/ dir use boto3. These scripts are used rarely, if at all.

Clean up the boto usage by standardizing on boto3.

**Comment by danstoner** [comment]
Switching to boto3 is nontrivial.  It is very different than boto2, equivalent to switching to a completely different library and that is how we should think of it (almost every call to any boto object/method would need to be modified in our code).

Boto docs say:

> Boto3, the next version of Boto, is now stable and recommended for general use. It can be used side-by-side with Boto in the same project, so it is easy to start using Boto3 in your existing projects as well as new projects.

Most likely that is exactly what we did and the scripts are examples of newer but isolated code where the developer chose to use Boto3. This seems fine to me.  If we were going to standardize it seems like we would bring those "rarely, if at all" scripts in-line with the main codebase, rather than the other way around.

Maybe setup.py should install both `boto` and `boto3` if we don't want the import in one of those scripts to fail.

**Sidenote, don't run those scripts without inspecting them first, at least one of them is destructive.**

Maybe we should remove un-used scripts from the codebase.

I couldn't find an indication of boto2 hitting end-of-life or maybe a more compelling reason to switch to boto3.  The authors say:

> As more users make the switch to Boto3, we expect to reduce our maintenance involvement over time. If we decide on a cutoff date or any significant changes to our maintenance plan, we will make pre-announcements well ahead of schedule to allow ample time for our users to adapt/migrate.

and I couldn't find any such announcements.  Could just be bad googling on my part though.

If we get into doing wholesale refactoring then we can surely consider this alternative S3-compatible library. Similarly if the boto support situation changes we would need to re-assess.

**Comment by danstoner** [comment]
Closing as wontfix.
