### ISSUE TITLE
Suffix of database determined by multiple configuration settings

### ISSUE THREAD

**Issue by mjcollin** [iDigBio/idb-backend#30]
There are two keys in the idigbio.json config file/object:

```
["postgres"]["db_suffix"]
["env"]["ENV"]
```

In `postgres_backend/__init__.py` the dbv connection for apidbpool is created based on `["env"]["ENV"]`:

```
suffix = pg_conf.pop("db_suffix", "_" + idb.config.ENV)
```

It appears that `["postgres"]["db_suffix"]` is unused in this repo but not sure about others. Examine and clean up if it is not used anywhere.

**Comment by danstoner** [comment]
I could be misreading, but I think ```["postgres"]["db_suffix"]` *is* used in ``idb/postgres_backend/__init__.py```

The config (including ```db_suffix```) is first copied into pg_conf and then referenced  from there.

https://github.com/iDigBio/idb-backend/blob/master/idb/postgres_backend/__init__.py#L25

Based on my testing, that pop command will use db_suffix if ENV happens to be empty.

```
In [19]: pg_conf = copy.deepcopy(idb.config.config[u"postgres"])

In [20]: pg_conf
Out[20]: 
{u'db_prefix': u'idb_',
 u'db_suffix': u'_prod',
 u'host': u'somehost.acis.ufl.edu',
 u'password': u'****',
 u'user': u'idigbio'}

In [21]: suffix

In [22]: suffix = pg_conf.pop("db_suffix", "_" + "" )

In [23]: suffix
Out[23]: u'_prod'

```

Code last touched in 2016.

https://github.com/iDigBio/idb-backend/commit/35bc31c1f742843f38215f08b5142d2c2d6b4828#diff-baed2ca7ac267e370a248ad63e97fde1


The dict.pop() modifies the dict, removing the element.  No idea why we are doing that instead of just using the values.

It seems deliberate because the "pop" style replaced "del" to remove those keys.

https://github.com/iDigBio/idb-backend/blob/173f0a12ed278bfcf327aa5b03240e3e0e56976c/idb/postgres_backend/__init__.py

**Comment by mjcollin** [comment]
Yes, you're right about pop(). I still can find any combination of code that allows me to load a config file other than idigbio.json though.

Closing as the config file format and use of the variable on this line are not the issue.
